//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/_TiltDrive/Input/TiltDriveControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace TiltDrive.Input
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/_TiltDrive/Input/TiltDriveControls.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @TiltDriveControls: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @TiltDriveControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""TiltDriveControls"",
    ""maps"": [
        {
            ""name"": ""Wheel"",
            ""id"": ""c227523d-a508-41e3-8a35-534ffcd81e5b"",
            ""actions"": [
                {
                    ""name"": ""Steer"",
                    ""type"": ""Value"",
                    ""id"": ""f1f9ff6a-c647-45cc-8644-63ed844822ee"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""78d695ea-4d48-4f4b-990f-ef2e377368ab"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""6f397f0a-2356-496c-b59e-04e5caf1ef8b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Value"",
                    ""id"": ""f1d3dfd4-7bde-4e45-a381-d01eb1e28b50"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GearUp"",
                    ""type"": ""Button"",
                    ""id"": ""8948994c-2c98-4ccb-834d-74c7958fba8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearDown"",
                    ""type"": ""Button"",
                    ""id"": ""95f73a5f-91b0-4a48-9e91-b9fff8e59d87"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear1"",
                    ""type"": ""Button"",
                    ""id"": ""37ed4a35-caa8-42ac-bd92-8e9516fdd725"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear2"",
                    ""type"": ""Button"",
                    ""id"": ""aac76bb0-5295-487e-b31e-b2e3b2aceff9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear3"",
                    ""type"": ""Button"",
                    ""id"": ""1eda9443-e1fa-4d37-8021-cf86812a6b54"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear4"",
                    ""type"": ""Button"",
                    ""id"": ""cf03ffc5-474a-4ec9-9fb2-0ca32f3ebc60"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear5"",
                    ""type"": ""Button"",
                    ""id"": ""20d2862a-25b6-486a-b4f8-07fc93cf6254"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gear6"",
                    ""type"": ""Button"",
                    ""id"": ""4c0eccb0-6cf7-410e-bca7-8869293be0b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reverse"",
                    ""type"": ""Button"",
                    ""id"": ""09536d9e-2337-4305-89c0-e8b11ab1f2b2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightsLow"",
                    ""type"": ""Button"",
                    ""id"": ""ac367cc6-5dd2-480e-9f4e-9e7a3d68ab6b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightsHigh"",
                    ""type"": ""Button"",
                    ""id"": ""0829da14-07f1-4902-8624-c050a37652fb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hazard"",
                    ""type"": ""Button"",
                    ""id"": ""c7c6d66c-28b2-4d23-bd0c-af47d79c1b76"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBlinker"",
                    ""type"": ""Button"",
                    ""id"": ""cf8f1584-8d07-459c-82bc-5ffd2da122d6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBlinker"",
                    ""type"": ""Button"",
                    ""id"": ""6b378cf3-e9b9-4737-a214-dc5584c68553"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EngineStart"",
                    ""type"": ""Button"",
                    ""id"": ""cb5a351b-863d-4956-aa7c-2712c544a16d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1ada1ac-dc52-420f-9525-b12c7e86c0c4"",
                    ""path"": ""<Joystick>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ef0d52d-c976-4e16-9dbf-07e322a710e2"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2cb9976-0a51-4a89-b11f-35941440f197"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a37245e2-8200-4802-ad34-cbd5ec06a6e3"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a18bb87-679c-4ec3-8b54-bb2966e466b8"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button13"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""461b2b5d-1357-4471-82a3-58891cb09930"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1544f790-d886-4e63-8613-413ed346694b"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button14"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66b60dea-3887-4362-88e1-a258490bb9e6"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bac3897-2c45-4eb3-81f9-d88e0f2d4131"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button15"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e8f3896-b7e5-4aeb-9701-c2c1a380fef7"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c2b9c54-a197-4e37-ab03-6e98ab5ba9ec"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button16"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15f8e8e4-ccc7-4341-bee3-8b7f8a6097c5"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05198aa4-411c-4a9a-b825-9c6a9faa70a0"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button17"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da2b48c7-cb6f-4982-9f7f-07daabd4cac3"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""580e576b-f420-4f87-b3c8-3d0b7406e606"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button18"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d7e2e8e-8f28-44bc-af63-315dd97340fa"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gear6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64318032-8364-437b-a988-6d6fa1daa413"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfee45f8-62a1-404f-b9f2-10354e1dcc4a"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3f3516a-a04d-459b-beac-372e33a1d85f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightsLow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17f05d25-4694-4fb2-aad0-cd6b1bd042ef"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightsHigh"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f0e8c70-b840-4768-9b0f-b559ead86488"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hazard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fab32399-cff3-4af1-ac36-32ed84cd5314"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button10"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBlinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f73f6c6-48c0-4c7d-8f91-c113c2c0cd4f"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBlinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10731150-ef53-410d-9756-55a5828f2a5e"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3fbdad91-877b-4d5c-91e7-d54408735b97"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5345b4aa-b295-444e-8501-8771f3276835"",
                    ""path"": ""<HID::Logitech G920 Driving Force Racing Wheel for Xbox One>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EngineStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""id"": ""8169033a-7daa-4d53-a9bf-65a68fbac80e"",
            ""actions"": [
                {
                    ""name"": ""Steer"",
                    ""type"": ""Value"",
                    ""id"": ""71f4d9cf-405d-425c-bc4a-13e981e49a2d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Throttle"",
                    ""type"": ""Value"",
                    ""id"": ""e9977bf7-d75f-4121-8f84-959af41d1255"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Value"",
                    ""id"": ""c6aae093-3c13-4729-a40a-6e9d99dc0459"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clutch"",
                    ""type"": ""Value"",
                    ""id"": ""f29b51d1-32b1-49d5-8675-a6d386112e7b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GearUp"",
                    ""type"": ""Button"",
                    ""id"": ""4ae56157-bc05-4c35-8eb7-62eb2133667a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GearDown"",
                    ""type"": ""Button"",
                    ""id"": ""5b8afdb7-78d1-428f-b2e5-3f60361b56e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightsLow"",
                    ""type"": ""Button"",
                    ""id"": ""1a9fe60d-7e3d-401d-8c0e-63d7ad06c7db"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightsHigh"",
                    ""type"": ""Button"",
                    ""id"": ""44e01622-25f3-40e5-9e54-0a5dab68e96d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hazard"",
                    ""type"": ""Button"",
                    ""id"": ""d8bfabeb-0631-47da-89e1-0a5ea272869f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBlinker"",
                    ""type"": ""Button"",
                    ""id"": ""ef791576-7bab-4c0f-b4e3-d9d9e745e688"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBlinker"",
                    ""type"": ""Button"",
                    ""id"": ""4372a713-f4dc-4513-a691-7d0d4bcb4c26"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EngineStart"",
                    ""type"": ""Button"",
                    ""id"": ""257cc56a-05cb-4d46-a485-1c6bc57c4895"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4ecfa834-193d-4d71-b94d-11c82aecb65a"",
                    ""path"": ""<XInputController>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Steer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""21c28363-645f-464e-b8ab-70aaf97079ee"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throttle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc24f839-9ebe-45da-90e5-3b8c12cec8ef"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05254f67-10a2-43d6-a9f6-5e9974af838a"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clutch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42b3bc2d-5ee8-4534-9454-a575ce3c3be6"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a161474f-1660-4966-82f2-b944bbf2dd9d"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GearDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f41974ea-c6c2-48f4-b774-5633e44f5415"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightsLow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4381afc6-d7ff-47a0-8ff9-0a97d8849dc8"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightsHigh"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0bcfbd8-7318-44e5-bf39-be0ae9a27058"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hazard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d1b2bb4-0dfc-4c66-86fc-08f060b9147a"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBlinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c109ea35-6fd3-42d9-8cd4-0711e5e3dedc"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBlinker"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fdacd3d-b889-451b-94c2-03a58c22d2ec"",
                    ""path"": ""<XInputController>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EngineStart"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Wheel
            m_Wheel = asset.FindActionMap("Wheel", throwIfNotFound: true);
            m_Wheel_Steer = m_Wheel.FindAction("Steer", throwIfNotFound: true);
            m_Wheel_Throttle = m_Wheel.FindAction("Throttle", throwIfNotFound: true);
            m_Wheel_Clutch = m_Wheel.FindAction("Clutch", throwIfNotFound: true);
            m_Wheel_Brake = m_Wheel.FindAction("Brake", throwIfNotFound: true);
            m_Wheel_GearUp = m_Wheel.FindAction("GearUp", throwIfNotFound: true);
            m_Wheel_GearDown = m_Wheel.FindAction("GearDown", throwIfNotFound: true);
            m_Wheel_Gear1 = m_Wheel.FindAction("Gear1", throwIfNotFound: true);
            m_Wheel_Gear2 = m_Wheel.FindAction("Gear2", throwIfNotFound: true);
            m_Wheel_Gear3 = m_Wheel.FindAction("Gear3", throwIfNotFound: true);
            m_Wheel_Gear4 = m_Wheel.FindAction("Gear4", throwIfNotFound: true);
            m_Wheel_Gear5 = m_Wheel.FindAction("Gear5", throwIfNotFound: true);
            m_Wheel_Gear6 = m_Wheel.FindAction("Gear6", throwIfNotFound: true);
            m_Wheel_Reverse = m_Wheel.FindAction("Reverse", throwIfNotFound: true);
            m_Wheel_LightsLow = m_Wheel.FindAction("LightsLow", throwIfNotFound: true);
            m_Wheel_LightsHigh = m_Wheel.FindAction("LightsHigh", throwIfNotFound: true);
            m_Wheel_Hazard = m_Wheel.FindAction("Hazard", throwIfNotFound: true);
            m_Wheel_LeftBlinker = m_Wheel.FindAction("LeftBlinker", throwIfNotFound: true);
            m_Wheel_RightBlinker = m_Wheel.FindAction("RightBlinker", throwIfNotFound: true);
            m_Wheel_EngineStart = m_Wheel.FindAction("EngineStart", throwIfNotFound: true);
            // Gamepad
            m_Gamepad = asset.FindActionMap("Gamepad", throwIfNotFound: true);
            m_Gamepad_Steer = m_Gamepad.FindAction("Steer", throwIfNotFound: true);
            m_Gamepad_Throttle = m_Gamepad.FindAction("Throttle", throwIfNotFound: true);
            m_Gamepad_Brake = m_Gamepad.FindAction("Brake", throwIfNotFound: true);
            m_Gamepad_Clutch = m_Gamepad.FindAction("Clutch", throwIfNotFound: true);
            m_Gamepad_GearUp = m_Gamepad.FindAction("GearUp", throwIfNotFound: true);
            m_Gamepad_GearDown = m_Gamepad.FindAction("GearDown", throwIfNotFound: true);
            m_Gamepad_LightsLow = m_Gamepad.FindAction("LightsLow", throwIfNotFound: true);
            m_Gamepad_LightsHigh = m_Gamepad.FindAction("LightsHigh", throwIfNotFound: true);
            m_Gamepad_Hazard = m_Gamepad.FindAction("Hazard", throwIfNotFound: true);
            m_Gamepad_LeftBlinker = m_Gamepad.FindAction("LeftBlinker", throwIfNotFound: true);
            m_Gamepad_RightBlinker = m_Gamepad.FindAction("RightBlinker", throwIfNotFound: true);
            m_Gamepad_EngineStart = m_Gamepad.FindAction("EngineStart", throwIfNotFound: true);
        }

        ~@TiltDriveControls()
        {
            UnityEngine.Debug.Assert(!m_Wheel.enabled, "This will cause a leak and performance issues, TiltDriveControls.Wheel.Disable() has not been called.");
            UnityEngine.Debug.Assert(!m_Gamepad.enabled, "This will cause a leak and performance issues, TiltDriveControls.Gamepad.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Wheel
        private readonly InputActionMap m_Wheel;
        private List<IWheelActions> m_WheelActionsCallbackInterfaces = new List<IWheelActions>();
        private readonly InputAction m_Wheel_Steer;
        private readonly InputAction m_Wheel_Throttle;
        private readonly InputAction m_Wheel_Clutch;
        private readonly InputAction m_Wheel_Brake;
        private readonly InputAction m_Wheel_GearUp;
        private readonly InputAction m_Wheel_GearDown;
        private readonly InputAction m_Wheel_Gear1;
        private readonly InputAction m_Wheel_Gear2;
        private readonly InputAction m_Wheel_Gear3;
        private readonly InputAction m_Wheel_Gear4;
        private readonly InputAction m_Wheel_Gear5;
        private readonly InputAction m_Wheel_Gear6;
        private readonly InputAction m_Wheel_Reverse;
        private readonly InputAction m_Wheel_LightsLow;
        private readonly InputAction m_Wheel_LightsHigh;
        private readonly InputAction m_Wheel_Hazard;
        private readonly InputAction m_Wheel_LeftBlinker;
        private readonly InputAction m_Wheel_RightBlinker;
        private readonly InputAction m_Wheel_EngineStart;
        /// <summary>
        /// Provides access to input actions defined in input action map "Wheel".
        /// </summary>
        public struct WheelActions
        {
            private @TiltDriveControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public WheelActions(@TiltDriveControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Steer".
            /// </summary>
            public InputAction @Steer => m_Wrapper.m_Wheel_Steer;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Throttle".
            /// </summary>
            public InputAction @Throttle => m_Wrapper.m_Wheel_Throttle;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Clutch".
            /// </summary>
            public InputAction @Clutch => m_Wrapper.m_Wheel_Clutch;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Brake".
            /// </summary>
            public InputAction @Brake => m_Wrapper.m_Wheel_Brake;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/GearUp".
            /// </summary>
            public InputAction @GearUp => m_Wrapper.m_Wheel_GearUp;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/GearDown".
            /// </summary>
            public InputAction @GearDown => m_Wrapper.m_Wheel_GearDown;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Gear1".
            /// </summary>
            public InputAction @Gear1 => m_Wrapper.m_Wheel_Gear1;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Gear2".
            /// </summary>
            public InputAction @Gear2 => m_Wrapper.m_Wheel_Gear2;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Gear3".
            /// </summary>
            public InputAction @Gear3 => m_Wrapper.m_Wheel_Gear3;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Gear4".
            /// </summary>
            public InputAction @Gear4 => m_Wrapper.m_Wheel_Gear4;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Gear5".
            /// </summary>
            public InputAction @Gear5 => m_Wrapper.m_Wheel_Gear5;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Gear6".
            /// </summary>
            public InputAction @Gear6 => m_Wrapper.m_Wheel_Gear6;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Reverse".
            /// </summary>
            public InputAction @Reverse => m_Wrapper.m_Wheel_Reverse;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/LightsLow".
            /// </summary>
            public InputAction @LightsLow => m_Wrapper.m_Wheel_LightsLow;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/LightsHigh".
            /// </summary>
            public InputAction @LightsHigh => m_Wrapper.m_Wheel_LightsHigh;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/Hazard".
            /// </summary>
            public InputAction @Hazard => m_Wrapper.m_Wheel_Hazard;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/LeftBlinker".
            /// </summary>
            public InputAction @LeftBlinker => m_Wrapper.m_Wheel_LeftBlinker;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/RightBlinker".
            /// </summary>
            public InputAction @RightBlinker => m_Wrapper.m_Wheel_RightBlinker;
            /// <summary>
            /// Provides access to the underlying input action "Wheel/EngineStart".
            /// </summary>
            public InputAction @EngineStart => m_Wrapper.m_Wheel_EngineStart;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Wheel; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="WheelActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(WheelActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="WheelActions" />
            public void AddCallbacks(IWheelActions instance)
            {
                if (instance == null || m_Wrapper.m_WheelActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_WheelActionsCallbackInterfaces.Add(instance);
                @Steer.started += instance.OnSteer;
                @Steer.performed += instance.OnSteer;
                @Steer.canceled += instance.OnSteer;
                @Throttle.started += instance.OnThrottle;
                @Throttle.performed += instance.OnThrottle;
                @Throttle.canceled += instance.OnThrottle;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @Brake.started += instance.OnBrake;
                @Brake.performed += instance.OnBrake;
                @Brake.canceled += instance.OnBrake;
                @GearUp.started += instance.OnGearUp;
                @GearUp.performed += instance.OnGearUp;
                @GearUp.canceled += instance.OnGearUp;
                @GearDown.started += instance.OnGearDown;
                @GearDown.performed += instance.OnGearDown;
                @GearDown.canceled += instance.OnGearDown;
                @Gear1.started += instance.OnGear1;
                @Gear1.performed += instance.OnGear1;
                @Gear1.canceled += instance.OnGear1;
                @Gear2.started += instance.OnGear2;
                @Gear2.performed += instance.OnGear2;
                @Gear2.canceled += instance.OnGear2;
                @Gear3.started += instance.OnGear3;
                @Gear3.performed += instance.OnGear3;
                @Gear3.canceled += instance.OnGear3;
                @Gear4.started += instance.OnGear4;
                @Gear4.performed += instance.OnGear4;
                @Gear4.canceled += instance.OnGear4;
                @Gear5.started += instance.OnGear5;
                @Gear5.performed += instance.OnGear5;
                @Gear5.canceled += instance.OnGear5;
                @Gear6.started += instance.OnGear6;
                @Gear6.performed += instance.OnGear6;
                @Gear6.canceled += instance.OnGear6;
                @Reverse.started += instance.OnReverse;
                @Reverse.performed += instance.OnReverse;
                @Reverse.canceled += instance.OnReverse;
                @LightsLow.started += instance.OnLightsLow;
                @LightsLow.performed += instance.OnLightsLow;
                @LightsLow.canceled += instance.OnLightsLow;
                @LightsHigh.started += instance.OnLightsHigh;
                @LightsHigh.performed += instance.OnLightsHigh;
                @LightsHigh.canceled += instance.OnLightsHigh;
                @Hazard.started += instance.OnHazard;
                @Hazard.performed += instance.OnHazard;
                @Hazard.canceled += instance.OnHazard;
                @LeftBlinker.started += instance.OnLeftBlinker;
                @LeftBlinker.performed += instance.OnLeftBlinker;
                @LeftBlinker.canceled += instance.OnLeftBlinker;
                @RightBlinker.started += instance.OnRightBlinker;
                @RightBlinker.performed += instance.OnRightBlinker;
                @RightBlinker.canceled += instance.OnRightBlinker;
                @EngineStart.started += instance.OnEngineStart;
                @EngineStart.performed += instance.OnEngineStart;
                @EngineStart.canceled += instance.OnEngineStart;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="WheelActions" />
            private void UnregisterCallbacks(IWheelActions instance)
            {
                @Steer.started -= instance.OnSteer;
                @Steer.performed -= instance.OnSteer;
                @Steer.canceled -= instance.OnSteer;
                @Throttle.started -= instance.OnThrottle;
                @Throttle.performed -= instance.OnThrottle;
                @Throttle.canceled -= instance.OnThrottle;
                @Clutch.started -= instance.OnClutch;
                @Clutch.performed -= instance.OnClutch;
                @Clutch.canceled -= instance.OnClutch;
                @Brake.started -= instance.OnBrake;
                @Brake.performed -= instance.OnBrake;
                @Brake.canceled -= instance.OnBrake;
                @GearUp.started -= instance.OnGearUp;
                @GearUp.performed -= instance.OnGearUp;
                @GearUp.canceled -= instance.OnGearUp;
                @GearDown.started -= instance.OnGearDown;
                @GearDown.performed -= instance.OnGearDown;
                @GearDown.canceled -= instance.OnGearDown;
                @Gear1.started -= instance.OnGear1;
                @Gear1.performed -= instance.OnGear1;
                @Gear1.canceled -= instance.OnGear1;
                @Gear2.started -= instance.OnGear2;
                @Gear2.performed -= instance.OnGear2;
                @Gear2.canceled -= instance.OnGear2;
                @Gear3.started -= instance.OnGear3;
                @Gear3.performed -= instance.OnGear3;
                @Gear3.canceled -= instance.OnGear3;
                @Gear4.started -= instance.OnGear4;
                @Gear4.performed -= instance.OnGear4;
                @Gear4.canceled -= instance.OnGear4;
                @Gear5.started -= instance.OnGear5;
                @Gear5.performed -= instance.OnGear5;
                @Gear5.canceled -= instance.OnGear5;
                @Gear6.started -= instance.OnGear6;
                @Gear6.performed -= instance.OnGear6;
                @Gear6.canceled -= instance.OnGear6;
                @Reverse.started -= instance.OnReverse;
                @Reverse.performed -= instance.OnReverse;
                @Reverse.canceled -= instance.OnReverse;
                @LightsLow.started -= instance.OnLightsLow;
                @LightsLow.performed -= instance.OnLightsLow;
                @LightsLow.canceled -= instance.OnLightsLow;
                @LightsHigh.started -= instance.OnLightsHigh;
                @LightsHigh.performed -= instance.OnLightsHigh;
                @LightsHigh.canceled -= instance.OnLightsHigh;
                @Hazard.started -= instance.OnHazard;
                @Hazard.performed -= instance.OnHazard;
                @Hazard.canceled -= instance.OnHazard;
                @LeftBlinker.started -= instance.OnLeftBlinker;
                @LeftBlinker.performed -= instance.OnLeftBlinker;
                @LeftBlinker.canceled -= instance.OnLeftBlinker;
                @RightBlinker.started -= instance.OnRightBlinker;
                @RightBlinker.performed -= instance.OnRightBlinker;
                @RightBlinker.canceled -= instance.OnRightBlinker;
                @EngineStart.started -= instance.OnEngineStart;
                @EngineStart.performed -= instance.OnEngineStart;
                @EngineStart.canceled -= instance.OnEngineStart;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="WheelActions.UnregisterCallbacks(IWheelActions)" />.
            /// </summary>
            /// <seealso cref="WheelActions.UnregisterCallbacks(IWheelActions)" />
            public void RemoveCallbacks(IWheelActions instance)
            {
                if (m_Wrapper.m_WheelActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="WheelActions.AddCallbacks(IWheelActions)" />
            /// <seealso cref="WheelActions.RemoveCallbacks(IWheelActions)" />
            /// <seealso cref="WheelActions.UnregisterCallbacks(IWheelActions)" />
            public void SetCallbacks(IWheelActions instance)
            {
                foreach (var item in m_Wrapper.m_WheelActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_WheelActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="WheelActions" /> instance referencing this action map.
        /// </summary>
        public WheelActions @Wheel => new WheelActions(this);

        // Gamepad
        private readonly InputActionMap m_Gamepad;
        private List<IGamepadActions> m_GamepadActionsCallbackInterfaces = new List<IGamepadActions>();
        private readonly InputAction m_Gamepad_Steer;
        private readonly InputAction m_Gamepad_Throttle;
        private readonly InputAction m_Gamepad_Brake;
        private readonly InputAction m_Gamepad_Clutch;
        private readonly InputAction m_Gamepad_GearUp;
        private readonly InputAction m_Gamepad_GearDown;
        private readonly InputAction m_Gamepad_LightsLow;
        private readonly InputAction m_Gamepad_LightsHigh;
        private readonly InputAction m_Gamepad_Hazard;
        private readonly InputAction m_Gamepad_LeftBlinker;
        private readonly InputAction m_Gamepad_RightBlinker;
        private readonly InputAction m_Gamepad_EngineStart;
        /// <summary>
        /// Provides access to input actions defined in input action map "Gamepad".
        /// </summary>
        public struct GamepadActions
        {
            private @TiltDriveControls m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public GamepadActions(@TiltDriveControls wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/Steer".
            /// </summary>
            public InputAction @Steer => m_Wrapper.m_Gamepad_Steer;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/Throttle".
            /// </summary>
            public InputAction @Throttle => m_Wrapper.m_Gamepad_Throttle;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/Brake".
            /// </summary>
            public InputAction @Brake => m_Wrapper.m_Gamepad_Brake;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/Clutch".
            /// </summary>
            public InputAction @Clutch => m_Wrapper.m_Gamepad_Clutch;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/GearUp".
            /// </summary>
            public InputAction @GearUp => m_Wrapper.m_Gamepad_GearUp;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/GearDown".
            /// </summary>
            public InputAction @GearDown => m_Wrapper.m_Gamepad_GearDown;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/LightsLow".
            /// </summary>
            public InputAction @LightsLow => m_Wrapper.m_Gamepad_LightsLow;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/LightsHigh".
            /// </summary>
            public InputAction @LightsHigh => m_Wrapper.m_Gamepad_LightsHigh;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/Hazard".
            /// </summary>
            public InputAction @Hazard => m_Wrapper.m_Gamepad_Hazard;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/LeftBlinker".
            /// </summary>
            public InputAction @LeftBlinker => m_Wrapper.m_Gamepad_LeftBlinker;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/RightBlinker".
            /// </summary>
            public InputAction @RightBlinker => m_Wrapper.m_Gamepad_RightBlinker;
            /// <summary>
            /// Provides access to the underlying input action "Gamepad/EngineStart".
            /// </summary>
            public InputAction @EngineStart => m_Wrapper.m_Gamepad_EngineStart;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_Gamepad; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="GamepadActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(GamepadActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="GamepadActions" />
            public void AddCallbacks(IGamepadActions instance)
            {
                if (instance == null || m_Wrapper.m_GamepadActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GamepadActionsCallbackInterfaces.Add(instance);
                @Steer.started += instance.OnSteer;
                @Steer.performed += instance.OnSteer;
                @Steer.canceled += instance.OnSteer;
                @Throttle.started += instance.OnThrottle;
                @Throttle.performed += instance.OnThrottle;
                @Throttle.canceled += instance.OnThrottle;
                @Brake.started += instance.OnBrake;
                @Brake.performed += instance.OnBrake;
                @Brake.canceled += instance.OnBrake;
                @Clutch.started += instance.OnClutch;
                @Clutch.performed += instance.OnClutch;
                @Clutch.canceled += instance.OnClutch;
                @GearUp.started += instance.OnGearUp;
                @GearUp.performed += instance.OnGearUp;
                @GearUp.canceled += instance.OnGearUp;
                @GearDown.started += instance.OnGearDown;
                @GearDown.performed += instance.OnGearDown;
                @GearDown.canceled += instance.OnGearDown;
                @LightsLow.started += instance.OnLightsLow;
                @LightsLow.performed += instance.OnLightsLow;
                @LightsLow.canceled += instance.OnLightsLow;
                @LightsHigh.started += instance.OnLightsHigh;
                @LightsHigh.performed += instance.OnLightsHigh;
                @LightsHigh.canceled += instance.OnLightsHigh;
                @Hazard.started += instance.OnHazard;
                @Hazard.performed += instance.OnHazard;
                @Hazard.canceled += instance.OnHazard;
                @LeftBlinker.started += instance.OnLeftBlinker;
                @LeftBlinker.performed += instance.OnLeftBlinker;
                @LeftBlinker.canceled += instance.OnLeftBlinker;
                @RightBlinker.started += instance.OnRightBlinker;
                @RightBlinker.performed += instance.OnRightBlinker;
                @RightBlinker.canceled += instance.OnRightBlinker;
                @EngineStart.started += instance.OnEngineStart;
                @EngineStart.performed += instance.OnEngineStart;
                @EngineStart.canceled += instance.OnEngineStart;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="GamepadActions" />
            private void UnregisterCallbacks(IGamepadActions instance)
            {
                @Steer.started -= instance.OnSteer;
                @Steer.performed -= instance.OnSteer;
                @Steer.canceled -= instance.OnSteer;
                @Throttle.started -= instance.OnThrottle;
                @Throttle.performed -= instance.OnThrottle;
                @Throttle.canceled -= instance.OnThrottle;
                @Brake.started -= instance.OnBrake;
                @Brake.performed -= instance.OnBrake;
                @Brake.canceled -= instance.OnBrake;
                @Clutch.started -= instance.OnClutch;
                @Clutch.performed -= instance.OnClutch;
                @Clutch.canceled -= instance.OnClutch;
                @GearUp.started -= instance.OnGearUp;
                @GearUp.performed -= instance.OnGearUp;
                @GearUp.canceled -= instance.OnGearUp;
                @GearDown.started -= instance.OnGearDown;
                @GearDown.performed -= instance.OnGearDown;
                @GearDown.canceled -= instance.OnGearDown;
                @LightsLow.started -= instance.OnLightsLow;
                @LightsLow.performed -= instance.OnLightsLow;
                @LightsLow.canceled -= instance.OnLightsLow;
                @LightsHigh.started -= instance.OnLightsHigh;
                @LightsHigh.performed -= instance.OnLightsHigh;
                @LightsHigh.canceled -= instance.OnLightsHigh;
                @Hazard.started -= instance.OnHazard;
                @Hazard.performed -= instance.OnHazard;
                @Hazard.canceled -= instance.OnHazard;
                @LeftBlinker.started -= instance.OnLeftBlinker;
                @LeftBlinker.performed -= instance.OnLeftBlinker;
                @LeftBlinker.canceled -= instance.OnLeftBlinker;
                @RightBlinker.started -= instance.OnRightBlinker;
                @RightBlinker.performed -= instance.OnRightBlinker;
                @RightBlinker.canceled -= instance.OnRightBlinker;
                @EngineStart.started -= instance.OnEngineStart;
                @EngineStart.performed -= instance.OnEngineStart;
                @EngineStart.canceled -= instance.OnEngineStart;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GamepadActions.UnregisterCallbacks(IGamepadActions)" />.
            /// </summary>
            /// <seealso cref="GamepadActions.UnregisterCallbacks(IGamepadActions)" />
            public void RemoveCallbacks(IGamepadActions instance)
            {
                if (m_Wrapper.m_GamepadActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="GamepadActions.AddCallbacks(IGamepadActions)" />
            /// <seealso cref="GamepadActions.RemoveCallbacks(IGamepadActions)" />
            /// <seealso cref="GamepadActions.UnregisterCallbacks(IGamepadActions)" />
            public void SetCallbacks(IGamepadActions instance)
            {
                foreach (var item in m_Wrapper.m_GamepadActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GamepadActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="GamepadActions" /> instance referencing this action map.
        /// </summary>
        public GamepadActions @Gamepad => new GamepadActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Wheel" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="WheelActions.AddCallbacks(IWheelActions)" />
        /// <seealso cref="WheelActions.RemoveCallbacks(IWheelActions)" />
        public interface IWheelActions
        {
            /// <summary>
            /// Method invoked when associated input action "Steer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSteer(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Throttle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnThrottle(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Clutch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnClutch(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Brake" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrake(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "GearUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGearUp(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "GearDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGearDown(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Gear1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGear1(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Gear2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGear2(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Gear3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGear3(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Gear4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGear4(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Gear5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGear5(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Gear6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGear6(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Reverse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnReverse(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LightsLow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLightsLow(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LightsHigh" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLightsHigh(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Hazard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnHazard(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftBlinker" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftBlinker(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightBlinker" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightBlinker(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "EngineStart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnEngineStart(InputAction.CallbackContext context);
        }
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Gamepad" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="GamepadActions.AddCallbacks(IGamepadActions)" />
        /// <seealso cref="GamepadActions.RemoveCallbacks(IGamepadActions)" />
        public interface IGamepadActions
        {
            /// <summary>
            /// Method invoked when associated input action "Steer" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSteer(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Throttle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnThrottle(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Brake" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnBrake(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Clutch" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnClutch(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "GearUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGearUp(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "GearDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnGearDown(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LightsLow" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLightsLow(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LightsHigh" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLightsHigh(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "Hazard" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnHazard(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "LeftBlinker" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnLeftBlinker(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "RightBlinker" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnRightBlinker(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "EngineStart" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnEngineStart(InputAction.CallbackContext context);
        }
    }
}
